----配置管理相关表-----
DROP TABLE TEDCC02;
DROP TABLE TEDCC03;

DROP TABLE TEDCM00;
DROP TABLE TEDCM01;
DROP TABLE TEDCM0001;

DROP TABLE TEDDBI0;
DROP TABLE TEDDBT0;
DROP TABLE TEDDBT1;
DROP TABLE TEDDBT3;
DROP TABLE TEDDBT5;
DROP TABLE TEIIT00;
DROP TABLE TEIIT10;

DROP TABLE TEDFA00;
DROP TABLE TEDFA01;
DROP TABLE TEDFA10;
DROP TABLE TEDFA60;
DROP TABLE TEDFA61;

DROP TABLE TEDNM01;
DROP TABLE TEDNM02;
DROP TABLE TEDNM03;
DROP TABLE TEDNM04;
DROP TABLE TEDNM05;
DROP TABLE TEDNM06;

DROP TABLE TEDPI01;
DROP TABLE TEDPI02;
DROP TABLE TEDPI03;
DROP TABLE TEDPI10;

DROP TABLE TEDPC01;
DROP TABLE TEDPC02;
DROP TABLE TEDPC03;
DROP TABLE TEDPC04;
DROP TABLE TEDPC05;

DROP TABLE ED_XM_EVENT;
DROP TABLE ED_XM_SERVICE;
DROP TABLE ED_XM_PARAM;
DROP TABLE ED_XM_EVENT_SERVICE_RELA;
DROP TABLE ED_XM_EVENT_ROUTE;
DROP TABLE ED_XM_EVENT_PARAM;
DROP TABLE ED_XM_2PC_LOG;

DROP TABLE TEDMDM2;
DROP TABLE TEDMDM3;
DROP TABLE TEDMDM4;

DROP TABLE TEUDM01;
DROP TABLE TEUDM02;

DROP TABLE TXSOG01;
DROP TABLE TXSOG0101;
DROP TABLE TXSOG02;
DROP TABLE TXSOG03;
DROP TABLE TXSOG07;

----任务管理相关表-----

DROP TABLE EJ_QRTZ_BLOB_TRIGGERS;
DROP TABLE EJ_QRTZ_CALENDARS;
DROP TABLE EJ_QRTZ_CRON_TRIGGERS;
DROP TABLE EJ_QRTZ_FIRED_TRIGGERS;
DROP TABLE EJ_QRTZ_LOCKS;
DROP TABLE EJ_QRTZ_LOGGING;
DROP TABLE EJ_QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE EJ_QRTZ_SCHEDULER_STATE;
DROP TABLE EJ_QRTZ_SIMPROP_TRIGGERS;
DROP TABLE EJ_QRTZ_SIMPLE_TRIGGERS;
DROP TABLE EJ_QRTZ_TRIGGERS;
DROP TABLE EJ_QRTZ_JOB_DETAILS;

----授权管理相关表-----
DROP TABLE XS_AUTHORIZATION;
DROP TABLE XS_DATAS_AUTHORIZATION;
DROP TABLE XS_RESOURCE;
DROP TABLE XS_RESOURCE_GROUP;
DROP TABLE XS_RESOURCE_GROUP_MEMBER;
DROP TABLE XS_USER;
DROP TABLE XS_USER_EXT;
DROP TABLE XS_USER_GROUP;
DROP TABLE XS_USER_GROUP_MEMBER;
DROP TABLE XS_DATAS_SQL;

----消息管理相关表-----
DROP TABLE EM_HISTORY;
DROP TABLE EM_HI_LOG;
DROP TABLE EM_TELE_METADATA;

----流程管理相关表-----
DROP TABLE TEWPD00;
DROP TABLE TEWPD01;
DROP TABLE TEWPD02;
DROP TABLE TEWPD03;
DROP TABLE TEWPD04;
DROP TABLE TEWPD05;
DROP TABLE TEWPD06;
DROP TABLE TEWPD07;
DROP TABLE TEWPD08;
DROP TABLE TEWPD09;
DROP TABLE TEWPD10;
DROP TABLE TEWPD11;
DROP TABLE TEWPD12;
DROP TABLE TEWPD13;
DROP TABLE TEWPD14;
DROP TABLE TEWPD15;
DROP TABLE TEWPG00;
DROP TABLE TEWPI00;
DROP TABLE TEWPI01;
DROP TABLE TEWPI02;
DROP TABLE TEWPT00;
DROP TABLE TEWPT01;
DROP TABLE TEWPT02;
DROP TABLE TEWPT03;
DROP TABLE HEWPI00;
DROP TABLE HEWPT00;



DROP TABLE ACT_GE_PROPERTY;
DROP TABLE ACT_RU_VARIABLE;
DROP TABLE ACT_RE_MODEL;
DROP TABLE ACT_RU_IDENTITYLINK;
DROP TABLE ACT_RU_TASK;
DROP TABLE ACT_RU_JOB;
DROP TABLE ACT_RU_EVENT_SUBSCR;
DROP TABLE ACT_EVT_LOG;
DROP TABLE ACT_HI_PROCINST;
DROP TABLE ACT_HI_ACTINST;
DROP TABLE ACT_HI_VARINST;
DROP TABLE ACT_HI_TASKINST;
DROP TABLE ACT_HI_DETAIL;
DROP TABLE ACT_HI_COMMENT;
DROP TABLE ACT_HI_ATTACHMENT;
DROP TABLE ACT_HI_IDENTITYLINK;
DROP TABLE ACT_ID_INFO;
DROP TABLE ACT_ID_MEMBERSHIP;
DROP TABLE ACT_ID_GROUP;
DROP TABLE ACT_ID_USER;
DROP TABLE ACT_GE_BYTEARRAY;
DROP TABLE ACT_RE_DEPLOYMENT;
DROP TABLE ACT_RU_EXECUTION;
DROP TABLE ACT_RE_PROCDEF;